version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  pinger:
    build: .
    container_name: sdl_laba_2
    env_file: .env
    volumes:
      - ./logs:/logs
    depends_on:
      - db

volumes:
  db_data:
